FROM nginx:alpine


COPY nginx.conf /etc/nginx/conf.d/default.conf
# COPY selfsigned.crt etc/nginx/ssl/selfsigned.crt
# COPY selfsigned.key etc/nginx/ssl/selfsigned.key

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
