services:
  authmicroservice:
    build:
      context: ./backend/AuthMicroservice
      dockerfile: dockerfile
    container_name: authservice
    ports:
      - "5001:5000"
    environment:
      - PORT=5000
      - GIN_MODE=debug
    depends_on:
      authdb:
        condition: service_healthy
    networks:
      - backend

  archivemicroservice:
    build:
      context: ./backend/ArchiveMicroservice
      dockerfile: dockerfile
    container_name: archiveservice
    ports:
      - "5002:5000"
    environment:
      - PORT=5000
      - GIN_MODE=debug
    depends_on:
      archivedb:
        condition: service_healthy
    networks:
      - backend

  authdb:
    image: postgres:14.5
    restart: always
    container_name: authdb
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: authdb
      POSTGRES_USER: authuser
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: "exit 0"
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    ports:
      - "5432:5432"
    volumes:
      - authdata:/var/lib/postgresql/data
      #- ./db/auth-init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

  archivedb:
    image: postgres:14.5
    restart: always
    container_name: archivedb
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: archivedb
      POSTGRES_USER: archiveuser
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: "exit 0"
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    ports:
      - "5433:5432"
    volumes:
      - archivedata:/var/lib/postgresql/data
      #- ./db/archive-init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

volumes:
  authdata:
  archivedata:

networks:
  backend:
    name: backend-network
    driver: bridge
