-- auth-init.sql

-- \i 'tables/auth.sql'
CREATE TABLE AUTH (
    ID SERIAL PRIMARY KEY,
    REGISTRATION_DT TIMESTAMP NOT NULL,
    LAST_LOGIN_DT TIMESTAMP,
    USERNAME TEXT NOT NULL UNIQUE,
    PASSHASH TEXT NOT NULL,
    SALT TEXT NOT NULL,
    EMAIL TEXT NOT NULL UNIQUE,
    FIRSTNAME TEXT,
    LASTNAME TEXT
);
-- Add more scripts as needed